# based off https://github.com/vegasbrianc/docker-compose-demo

version: '3'
services:
  web:
    image: docker-intro-image
    ports:
      - 8080
    networks:
      - front-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  front-tier:
